#define SQLITE3_ORG_FN_IDX_SQLITE3_AGGREGATE_CONTEXT                     0
#define SQLITE3_ORG_FN_IDX_SQLITE3_AGGREGATE_COUNT                       1
#define SQLITE3_ORG_FN_IDX_SQLITE3_AUTO_EXTENSION                        2
#define SQLITE3_ORG_FN_IDX_SQLITE3_AUTOVACUUM_PAGES                      3
#define SQLITE3_ORG_FN_IDX_SQLITE3_BACKUP_FINISH                         4
#define SQLITE3_ORG_FN_IDX_SQLITE3_BACKUP_INIT                           5
#define SQLITE3_ORG_FN_IDX_SQLITE3_BACKUP_PAGECOUNT                      6
#define SQLITE3_ORG_FN_IDX_SQLITE3_BACKUP_REMAINING                      7
#define SQLITE3_ORG_FN_IDX_SQLITE3_BACKUP_STEP                           8
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_BLOB                             9
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_BLOB64                           10
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_DOUBLE                           11
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_INT                              12
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_INT64                            13
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_NULL                             14
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_PARAMETER_COUNT                  15
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_PARAMETER_INDEX                  16
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_PARAMETER_NAME                   17
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_POINTER                          18
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_TEXT                             19
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_TEXT16                           20
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_TEXT64                           21
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_VALUE                            22
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_ZEROBLOB                         23
#define SQLITE3_ORG_FN_IDX_SQLITE3_BIND_ZEROBLOB64                       24
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_BYTES                            25
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_CLOSE                            26
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_OPEN                             27
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_READ                             28
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_REOPEN                           29
#define SQLITE3_ORG_FN_IDX_SQLITE3_BLOB_WRITE                            30
#define SQLITE3_ORG_FN_IDX_SQLITE3_BUSY_HANDLER                          31
#define SQLITE3_ORG_FN_IDX_SQLITE3_BUSY_TIMEOUT                          32
#define SQLITE3_ORG_FN_IDX_SQLITE3_CANCEL_AUTO_EXTENSION                 33
#define SQLITE3_ORG_FN_IDX_SQLITE3_CHANGES                               34
#define SQLITE3_ORG_FN_IDX_SQLITE3_CHANGES64                             35
#define SQLITE3_ORG_FN_IDX_SQLITE3_CLEAR_BINDINGS                        36
#define SQLITE3_ORG_FN_IDX_SQLITE3_CLOSE                                 37
#define SQLITE3_ORG_FN_IDX_SQLITE3_CLOSE_V2                              38
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLLATION_NEEDED                      39
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLLATION_NEEDED16                    40
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_BLOB                           41
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_BYTES                          42
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_BYTES16                        43
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_COUNT                          44
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_DATABASE_NAME                  45
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_DATABASE_NAME16                46
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_DECLTYPE                       47
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_DECLTYPE16                     48
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_DOUBLE                         49
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_INT                            50
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_INT64                          51
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_NAME                           52
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_NAME16                         53
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_ORIGIN_NAME                    54
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_ORIGIN_NAME16                  55
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_TABLE_NAME                     56
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_TABLE_NAME16                   57
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_TEXT                           58
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_TEXT16                         59
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_TYPE                           60
#define SQLITE3_ORG_FN_IDX_SQLITE3_COLUMN_VALUE                          61
#define SQLITE3_ORG_FN_IDX_SQLITE3_COMMIT_HOOK                           62
#define SQLITE3_ORG_FN_IDX_SQLITE3_COMPILEOPTION_GET                     63
#define SQLITE3_ORG_FN_IDX_SQLITE3_COMPILEOPTION_USED                    64
#define SQLITE3_ORG_FN_IDX_SQLITE3_COMPLETE                              65
#define SQLITE3_ORG_FN_IDX_SQLITE3_COMPLETE16                            66
#define SQLITE3_ORG_FN_IDX_SQLITE3_CONTEXT_DB_HANDLE                     67
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_COLLATION                      68
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_COLLATION16                    69
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_COLLATION_V2                   70
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_FILENAME                       71
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_FUNCTION                       72
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_FUNCTION16                     73
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_FUNCTION_V2                    74
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_MODULE                         75
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_MODULE_V2                      76
#define SQLITE3_ORG_FN_IDX_SQLITE3_CREATE_WINDOW_FUNCTION                77
#define SQLITE3_ORG_FN_IDX_SQLITE3_DATA_COUNT                            78
#define SQLITE3_ORG_FN_IDX_SQLITE3_DATABASE_FILE_OBJECT                  79
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_CACHEFLUSH                         80
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_FILENAME                           81
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_HANDLE                             82
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_MUTEX                              83
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_READONLY                           84
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_RELEASE_MEMORY                     85
#define SQLITE3_ORG_FN_IDX_SQLITE3_DB_STATUS                             86
#define SQLITE3_ORG_FN_IDX_SQLITE3_DECLARE_VTAB                          87
#define SQLITE3_ORG_FN_IDX_SQLITE3_DESERIALIZE                           88
#define SQLITE3_ORG_FN_IDX_SQLITE3_DROP_MODULES                          89
#define SQLITE3_ORG_FN_IDX_SQLITE3_ENABLE_LOAD_EXTENSION                 90
#define SQLITE3_ORG_FN_IDX_SQLITE3_ENABLE_SHARED_CACHE                   91
#define SQLITE3_ORG_FN_IDX_SQLITE3_ERRCODE                               92
#define SQLITE3_ORG_FN_IDX_SQLITE3_ERRMSG                                93
#define SQLITE3_ORG_FN_IDX_SQLITE3_ERRMSG16                              94
#define SQLITE3_ORG_FN_IDX_SQLITE3_ERROR_OFFSET                          95
#define SQLITE3_ORG_FN_IDX_SQLITE3_ERRSTR                                96
#define SQLITE3_ORG_FN_IDX_SQLITE3_EXEC                                  97
#define SQLITE3_ORG_FN_IDX_SQLITE3_EXPANDED_SQL                          98
#define SQLITE3_ORG_FN_IDX_SQLITE3_EXPIRED                               99
#define SQLITE3_ORG_FN_IDX_SQLITE3_EXTENDED_ERRCODE                      100
#define SQLITE3_ORG_FN_IDX_SQLITE3_EXTENDED_RESULT_CODES                 101
#define SQLITE3_ORG_FN_IDX_SQLITE3_FILE_CONTROL                          102
#define SQLITE3_ORG_FN_IDX_SQLITE3_FILENAME_DATABASE                     103
#define SQLITE3_ORG_FN_IDX_SQLITE3_FILENAME_JOURNAL                      104
#define SQLITE3_ORG_FN_IDX_SQLITE3_FILENAME_WAL                          105
#define SQLITE3_ORG_FN_IDX_SQLITE3_FINALIZE                              106
#define SQLITE3_ORG_FN_IDX_SQLITE3_FREE                                  107
#define SQLITE3_ORG_FN_IDX_SQLITE3_FREE_FILENAME                         108
#define SQLITE3_ORG_FN_IDX_SQLITE3_FREE_TABLE                            109
#define SQLITE3_ORG_FN_IDX_SQLITE3_GET_AUTOCOMMIT                        110
#define SQLITE3_ORG_FN_IDX_SQLITE3_GET_AUXDATA                           111
#define SQLITE3_ORG_FN_IDX_SQLITE3_GET_TABLE                             112
#define SQLITE3_ORG_FN_IDX_SQLITE3_GLOBAL_RECOVER                        113
#define SQLITE3_ORG_FN_IDX_SQLITE3_HARD_HEAP_LIMIT64                     114
#define SQLITE3_ORG_FN_IDX_SQLITE3_INITIALIZE                            115
#define SQLITE3_ORG_FN_IDX_SQLITE3_INTERRUPT                             116
#define SQLITE3_ORG_FN_IDX_SQLITE3_KEY                                   117
#define SQLITE3_ORG_FN_IDX_SQLITE3_KEY_V2                                118
#define SQLITE3_ORG_FN_IDX_SQLITE3_KEYWORD_CHECK                         119
#define SQLITE3_ORG_FN_IDX_SQLITE3_KEYWORD_COUNT                         120
#define SQLITE3_ORG_FN_IDX_SQLITE3_KEYWORD_NAME                          121
#define SQLITE3_ORG_FN_IDX_SQLITE3_LAST_INSERT_ROWID                     122
#define SQLITE3_ORG_FN_IDX_SQLITE3_LIBVERSION                            123
#define SQLITE3_ORG_FN_IDX_SQLITE3_LIBVERSION_NUMBER                     124
#define SQLITE3_ORG_FN_IDX_SQLITE3_LIMIT                                 125
#define SQLITE3_ORG_FN_IDX_SQLITE3_LOAD_EXTENSION                        126
#define SQLITE3_ORG_FN_IDX_SQLITE3_MALLOC                                127
#define SQLITE3_ORG_FN_IDX_SQLITE3_MALLOC64                              128
#define SQLITE3_ORG_FN_IDX_SQLITE3_MEMORY_ALARM                          129
#define SQLITE3_ORG_FN_IDX_SQLITE3_MEMORY_HIGHWATER                      130
#define SQLITE3_ORG_FN_IDX_SQLITE3_MEMORY_USED                           131
#define SQLITE3_ORG_FN_IDX_SQLITE3_MSIZE                                 132
#define SQLITE3_ORG_FN_IDX_SQLITE3_MUTEX_ALLOC                           133
#define SQLITE3_ORG_FN_IDX_SQLITE3_MUTEX_ENTER                           134
#define SQLITE3_ORG_FN_IDX_SQLITE3_MUTEX_FREE                            135
#define SQLITE3_ORG_FN_IDX_SQLITE3_MUTEX_LEAVE                           136
#define SQLITE3_ORG_FN_IDX_SQLITE3_MUTEX_TRY                             137
#define SQLITE3_ORG_FN_IDX_SQLITE3_NEXT_STMT                             138
#define SQLITE3_ORG_FN_IDX_SQLITE3_OPEN                                  139
#define SQLITE3_ORG_FN_IDX_SQLITE3_OPEN16                                140
#define SQLITE3_ORG_FN_IDX_SQLITE3_OPEN_V2                               141
#define SQLITE3_ORG_FN_IDX_SQLITE3_OS_END                                142
#define SQLITE3_ORG_FN_IDX_SQLITE3_OS_INIT                               143
#define SQLITE3_ORG_FN_IDX_SQLITE3_OVERLOAD_FUNCTION                     144
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE                               145
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE16                             146
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE16_V2                          147
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE16_V3                          148
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE_V2                            149
#define SQLITE3_ORG_FN_IDX_SQLITE3_PREPARE_V3                            150
#define SQLITE3_ORG_FN_IDX_SQLITE3_PROFILE                               151
#define SQLITE3_ORG_FN_IDX_SQLITE3_PROGRESS_HANDLER                      152
#define SQLITE3_ORG_FN_IDX_SQLITE3_RANDOMNESS                            153
#define SQLITE3_ORG_FN_IDX_SQLITE3_REALLOC                               154
#define SQLITE3_ORG_FN_IDX_SQLITE3_REALLOC64                             155
#define SQLITE3_ORG_FN_IDX_SQLITE3_REKEY                                 156
#define SQLITE3_ORG_FN_IDX_SQLITE3_REKEY_V2                              157
#define SQLITE3_ORG_FN_IDX_SQLITE3_RELEASE_MEMORY                        158
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESET                                 159
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESET_AUTO_EXTENSION                  160
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_BLOB                           161
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_BLOB64                         162
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_DOUBLE                         163
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ERROR                          164
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ERROR16                        165
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ERROR_CODE                     166
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ERROR_NOMEM                    167
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ERROR_TOOBIG                   168
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_INT                            169
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_INT64                          170
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_NULL                           171
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_POINTER                        172
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_SUBTYPE                        173
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_TEXT                           174
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_TEXT16                         175
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_TEXT16BE                       176
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_TEXT16LE                       177
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_TEXT64                         178
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_VALUE                          179
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ZEROBLOB                       180
#define SQLITE3_ORG_FN_IDX_SQLITE3_RESULT_ZEROBLOB64                     181
#define SQLITE3_ORG_FN_IDX_SQLITE3_ROLLBACK_HOOK                         182
#define SQLITE3_ORG_FN_IDX_SQLITE3_RTREE_GEOMETRY_CALLBACK               183
#define SQLITE3_ORG_FN_IDX_SQLITE3_RTREE_QUERY_CALLBACK                  184
#define SQLITE3_ORG_FN_IDX_SQLITE3_SERIALIZE                             185
#define SQLITE3_ORG_FN_IDX_SQLITE3_SET_AUTHORIZER                        186
#define SQLITE3_ORG_FN_IDX_SQLITE3_SET_AUXDATA                           187
#define SQLITE3_ORG_FN_IDX_SQLITE3_SET_LAST_INSERT_ROWID                 188
#define SQLITE3_ORG_FN_IDX_SQLITE3_SHUTDOWN                              189
#define SQLITE3_ORG_FN_IDX_SQLITE3_SLEEP                                 190
#define SQLITE3_ORG_FN_IDX_SQLITE3_SNAPSHOT_CMP                          191
#define SQLITE3_ORG_FN_IDX_SQLITE3_SNAPSHOT_FREE                         192
#define SQLITE3_ORG_FN_IDX_SQLITE3_SNAPSHOT_GET                          193
#define SQLITE3_ORG_FN_IDX_SQLITE3_SNAPSHOT_OPEN                         194
#define SQLITE3_ORG_FN_IDX_SQLITE3_SNAPSHOT_RECOVER                      195
#define SQLITE3_ORG_FN_IDX_SQLITE3_SOFT_HEAP_LIMIT                       196
#define SQLITE3_ORG_FN_IDX_SQLITE3_SOFT_HEAP_LIMIT64                     197
#define SQLITE3_ORG_FN_IDX_SQLITE3_SOURCEID                              198
#define SQLITE3_ORG_FN_IDX_SQLITE3_SQL                                   199
#define SQLITE3_ORG_FN_IDX_SQLITE3_STATUS                                200
#define SQLITE3_ORG_FN_IDX_SQLITE3_STATUS64                              201
#define SQLITE3_ORG_FN_IDX_SQLITE3_STEP                                  202
#define SQLITE3_ORG_FN_IDX_SQLITE3_STMT_BUSY                             203
#define SQLITE3_ORG_FN_IDX_SQLITE3_STMT_ISEXPLAIN                        204
#define SQLITE3_ORG_FN_IDX_SQLITE3_STMT_READONLY                         205
#define SQLITE3_ORG_FN_IDX_SQLITE3_STMT_STATUS                           206
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_APPEND                            207
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_APPENDALL                         208
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_APPENDCHAR                        209
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_ERRCODE                           210
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_FINISH                            211
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_LENGTH                            212
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_NEW                               213
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_RESET                             214
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_VALUE                             215
#define SQLITE3_ORG_FN_IDX_SQLITE3_STR_VAPPENDF                          216
#define SQLITE3_ORG_FN_IDX_SQLITE3_STRGLOB                               217
#define SQLITE3_ORG_FN_IDX_SQLITE3_STRICMP                               218
#define SQLITE3_ORG_FN_IDX_SQLITE3_STRLIKE                               219
#define SQLITE3_ORG_FN_IDX_SQLITE3_STRNICMP                              220
#define SQLITE3_ORG_FN_IDX_SQLITE3_SYSTEM_ERRNO                          221
#define SQLITE3_ORG_FN_IDX_SQLITE3_TABLE_COLUMN_METADATA                 222
#define SQLITE3_ORG_FN_IDX_SQLITE3_THREAD_CLEANUP                        223
#define SQLITE3_ORG_FN_IDX_SQLITE3_THREADSAFE                            224
#define SQLITE3_ORG_FN_IDX_SQLITE3_TOTAL_CHANGES                         225
#define SQLITE3_ORG_FN_IDX_SQLITE3_TOTAL_CHANGES64                       226
#define SQLITE3_ORG_FN_IDX_SQLITE3_TRACE                                 227
#define SQLITE3_ORG_FN_IDX_SQLITE3_TRACE_V2                              228
#define SQLITE3_ORG_FN_IDX_SQLITE3_TRANSFER_BINDINGS                     229
#define SQLITE3_ORG_FN_IDX_SQLITE3_TXN_STATE                             230
#define SQLITE3_ORG_FN_IDX_SQLITE3_UPDATE_HOOK                           231
#define SQLITE3_ORG_FN_IDX_SQLITE3_URI_BOOLEAN                           232
#define SQLITE3_ORG_FN_IDX_SQLITE3_URI_INT64                             233
#define SQLITE3_ORG_FN_IDX_SQLITE3_URI_KEY                               234
#define SQLITE3_ORG_FN_IDX_SQLITE3_URI_PARAMETER                         235
#define SQLITE3_ORG_FN_IDX_SQLITE3_USER_DATA                             236
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_BLOB                            237
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_BYTES                           238
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_BYTES16                         239
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_DOUBLE                          240
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_DUP                             241
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_FREE                            242
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_FROMBIND                        243
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_INT                             244
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_INT64                           245
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_NOCHANGE                        246
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_NUMERIC_TYPE                    247
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_POINTER                         248
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_SUBTYPE                         249
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_TEXT                            250
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_TEXT16                          251
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_TEXT16BE                        252
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_TEXT16LE                        253
#define SQLITE3_ORG_FN_IDX_SQLITE3_VALUE_TYPE                            254
#define SQLITE3_ORG_FN_IDX_SQLITE3_VFS_FIND                              255
#define SQLITE3_ORG_FN_IDX_SQLITE3_VFS_REGISTER                          256
#define SQLITE3_ORG_FN_IDX_SQLITE3_VFS_UNREGISTER                        257
#define SQLITE3_ORG_FN_IDX_SQLITE3_VMPRINTF                              258
#define SQLITE3_ORG_FN_IDX_SQLITE3_VSNPRINTF                             259
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_COLLATION                        260
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_DISTINCT                         261
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_IN                               262
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_IN_FIRST                         263
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_IN_NEXT                          264
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_NOCHANGE                         265
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_ON_CONFLICT                      266
#define SQLITE3_ORG_FN_IDX_SQLITE3_VTAB_RHS_VALUE                        267
#define SQLITE3_ORG_FN_IDX_SQLITE3_WAL_AUTOCHECKPOINT                    268
#define SQLITE3_ORG_FN_IDX_SQLITE3_WAL_CHECKPOINT                        269
#define SQLITE3_ORG_FN_IDX_SQLITE3_WAL_CHECKPOINT_V2                     270
#define SQLITE3_ORG_FN_IDX_SQLITE3_WAL_HOOK                              271
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_IS_NT                           272
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_MBCS_TO_UTF8                    273
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_MBCS_TO_UTF8_V2                 274
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_SET_DIRECTORY                   275
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_SET_DIRECTORY16                 276
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_SET_DIRECTORY8                  277
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_SLEEP                           278
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_UNICODE_TO_UTF8                 279
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_UTF8_TO_MBCS                    280
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_UTF8_TO_MBCS_V2                 281
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_UTF8_TO_UNICODE                 282
#define SQLITE3_ORG_FN_IDX_SQLITE3_WIN32_WRITE_DEBUG                     283

