typedef void* (*sqlite3_aggregate_context_fnptr_t)(sqlite3_context*, int);
typedef int (*sqlite3_aggregate_count_fnptr_t)(sqlite3_context*);
typedef int (*sqlite3_auto_extension_fnptr_t)(void (*)(void));
typedef int (*sqlite3_autovacuum_pages_fnptr_t)(sqlite3*, unsigned int (*)(void*, const char*, unsigned, unsigned, unsigned), void*, void (*)(void*));
typedef int (*sqlite3_backup_finish_fnptr_t)(sqlite3_backup*);
typedef sqlite3_backup* (*sqlite3_backup_init_fnptr_t)(sqlite3*, const char*, sqlite3*, const char*);
typedef int (*sqlite3_backup_pagecount_fnptr_t)(sqlite3_backup*);
typedef int (*sqlite3_backup_remaining_fnptr_t)(sqlite3_backup*);
typedef int (*sqlite3_backup_step_fnptr_t)(sqlite3_backup*, int);
typedef int (*sqlite3_bind_blob_fnptr_t)(sqlite3_stmt*, int, const void*, int, void (*)(void*));
typedef int (*sqlite3_bind_blob64_fnptr_t)(sqlite3_stmt*, int, const void*, sqlite3_uint64, void (*)(void*));
typedef int (*sqlite3_bind_double_fnptr_t)(sqlite3_stmt*, int, double);
typedef int (*sqlite3_bind_int_fnptr_t)(sqlite3_stmt*, int, int);
typedef int (*sqlite3_bind_int64_fnptr_t)(sqlite3_stmt*, int, sqlite_int64);
typedef int (*sqlite3_bind_null_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_bind_parameter_count_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_bind_parameter_index_fnptr_t)(sqlite3_stmt*, const char*);
typedef const char* (*sqlite3_bind_parameter_name_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_bind_pointer_fnptr_t)(sqlite3_stmt*, int, void*, const char*, void (*)(void*));
typedef int (*sqlite3_bind_text_fnptr_t)(sqlite3_stmt*, int, const char*, int, void (*)(void*));
typedef int (*sqlite3_bind_text16_fnptr_t)(sqlite3_stmt*, int, const void*, int, void (*)(void*));
typedef int (*sqlite3_bind_text64_fnptr_t)(sqlite3_stmt*, int, const char*, sqlite3_uint64, void (*)(void*), unsigned);
typedef int (*sqlite3_bind_value_fnptr_t)(sqlite3_stmt*, int, const sqlite3_value*);
typedef int (*sqlite3_bind_zeroblob_fnptr_t)(sqlite3_stmt*, int, int);
typedef int (*sqlite3_bind_zeroblob64_fnptr_t)(sqlite3_stmt*, int, sqlite3_uint64);
typedef int (*sqlite3_blob_bytes_fnptr_t)(sqlite3_blob*);
typedef int (*sqlite3_blob_close_fnptr_t)(sqlite3_blob*);
typedef int (*sqlite3_blob_open_fnptr_t)(sqlite3*, const char*, const char*, const char*, sqlite3_int64, int, sqlite3_blob**);
typedef int (*sqlite3_blob_read_fnptr_t)(sqlite3_blob*, void*, int, int);
typedef int (*sqlite3_blob_reopen_fnptr_t)(sqlite3_blob*, sqlite3_int64);
typedef int (*sqlite3_blob_write_fnptr_t)(sqlite3_blob*, const void*, int, int);
typedef int (*sqlite3_busy_handler_fnptr_t)(sqlite3*, int (*)(void*, int), void*);
typedef int (*sqlite3_busy_timeout_fnptr_t)(sqlite3*, int);
typedef int (*sqlite3_cancel_auto_extension_fnptr_t)(void (*)(void));
typedef int (*sqlite3_changes_fnptr_t)(sqlite3*);
typedef sqlite3_int64 (*sqlite3_changes64_fnptr_t)(sqlite3*);
typedef int (*sqlite3_clear_bindings_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_close_fnptr_t)(sqlite3*);
typedef int (*sqlite3_close_v2_fnptr_t)(sqlite3*);
typedef int (*sqlite3_collation_needed_fnptr_t)(sqlite3*, void*, void (*)(void*, sqlite3*, int, const char*));
typedef int (*sqlite3_collation_needed16_fnptr_t)(sqlite3*, void*, void (*)(void*, sqlite3*, int, const void*));
typedef const void* (*sqlite3_column_blob_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_column_bytes_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_column_bytes16_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_column_count_fnptr_t)(sqlite3_stmt*);
typedef const char* (*sqlite3_column_database_name_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_database_name16_fnptr_t)(sqlite3_stmt*, int);
typedef const char* (*sqlite3_column_decltype_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_decltype16_fnptr_t)(sqlite3_stmt*, int);
typedef double (*sqlite3_column_double_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_column_int_fnptr_t)(sqlite3_stmt*, int);
typedef sqlite_int64 (*sqlite3_column_int64_fnptr_t)(sqlite3_stmt*, int);
typedef const char* (*sqlite3_column_name_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_name16_fnptr_t)(sqlite3_stmt*, int);
typedef const char* (*sqlite3_column_origin_name_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_origin_name16_fnptr_t)(sqlite3_stmt*, int);
typedef const char* (*sqlite3_column_table_name_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_table_name16_fnptr_t)(sqlite3_stmt*, int);
typedef const unsigned char* (*sqlite3_column_text_fnptr_t)(sqlite3_stmt*, int);
typedef const void* (*sqlite3_column_text16_fnptr_t)(sqlite3_stmt*, int);
typedef int (*sqlite3_column_type_fnptr_t)(sqlite3_stmt*, int);
typedef sqlite3_value* (*sqlite3_column_value_fnptr_t)(sqlite3_stmt*, int);
typedef void* (*sqlite3_commit_hook_fnptr_t)(sqlite3*, int (*)(void*), void*);
typedef const char* (*sqlite3_compileoption_get_fnptr_t)(int);
typedef int (*sqlite3_compileoption_used_fnptr_t)(const char*);
typedef int (*sqlite3_complete_fnptr_t)(const char*);
typedef int (*sqlite3_complete16_fnptr_t)(const void*);
typedef int (*sqlite3_config_fnptr_t)(int, ...);
typedef sqlite3* (*sqlite3_context_db_handle_fnptr_t)(sqlite3_context*);
typedef int (*sqlite3_create_collation_fnptr_t)(sqlite3*, const char*, int, void*, int (*)(void*, int, const void*, int, const void*));
typedef int (*sqlite3_create_collation_v2_fnptr_t)(sqlite3*, const char*, int, void*, int (*)(void*, int, const void*, int, const void*), void (*)(void*));
typedef int (*sqlite3_create_collation16_fnptr_t)(sqlite3*, const void*, int, void*, int (*)(void*, int, const void*, int, const void*));
typedef const char* (*sqlite3_create_filename_fnptr_t)(const char*, const char*, const char*, int, const char**);
typedef int (*sqlite3_create_function_fnptr_t)(sqlite3*, const char*, int, int, void*, void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*));
typedef int (*sqlite3_create_function_v2_fnptr_t)(sqlite3*, const char*, int, int, void*, void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*), void (*)(void*));
typedef int (*sqlite3_create_function16_fnptr_t)(sqlite3*, const void*, int, int, void*, void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*));
typedef int (*sqlite3_create_module_fnptr_t)(sqlite3*, const char*, const sqlite3_module*, void*);
typedef int (*sqlite3_create_module_v2_fnptr_t)(sqlite3*, const char*, const sqlite3_module*, void*, void (*)(void*));
typedef int (*sqlite3_create_window_function_fnptr_t)(sqlite3*, const char*, int, int, void*, void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(sqlite3_context*), void (*)(sqlite3_context*), void (*)(sqlite3_context*, int, sqlite3_value**), void (*)(void*));
typedef int (*sqlite3_data_count_fnptr_t)(sqlite3_stmt*);
typedef sqlite3_file* (*sqlite3_database_file_object_fnptr_t)(const char*);
typedef int (*sqlite3_db_cacheflush_fnptr_t)(sqlite3*);
typedef int (*sqlite3_db_config_fnptr_t)(sqlite3*, int, ...);
typedef const char* (*sqlite3_db_filename_fnptr_t)(sqlite3*, const char*);
typedef sqlite3* (*sqlite3_db_handle_fnptr_t)(sqlite3_stmt*);
typedef sqlite3_mutex* (*sqlite3_db_mutex_fnptr_t)(sqlite3*);
typedef int (*sqlite3_db_readonly_fnptr_t)(sqlite3*, const char*);
typedef int (*sqlite3_db_release_memory_fnptr_t)(sqlite3*);
typedef int (*sqlite3_db_status_fnptr_t)(sqlite3*, int, int*, int*, int);
typedef int (*sqlite3_declare_vtab_fnptr_t)(sqlite3*, const char*);
typedef int (*sqlite3_deserialize_fnptr_t)(sqlite3*, const char*, unsigned char*, sqlite3_int64, sqlite3_int64, unsigned);
typedef int (*sqlite3_drop_modules_fnptr_t)(sqlite3*, const char**);
typedef int (*sqlite3_enable_load_extension_fnptr_t)(sqlite3*, int);
typedef int (*sqlite3_enable_shared_cache_fnptr_t)(int);
typedef int (*sqlite3_errcode_fnptr_t)(sqlite3*);
typedef const char* (*sqlite3_errmsg_fnptr_t)(sqlite3*);
typedef const void* (*sqlite3_errmsg16_fnptr_t)(sqlite3*);
typedef int (*sqlite3_error_offset_fnptr_t)(sqlite3*);
typedef const char* (*sqlite3_errstr_fnptr_t)(int);
typedef int (*sqlite3_exec_fnptr_t)(sqlite3*, const char*, sqlite3_callback, void*, char**);
typedef char* (*sqlite3_expanded_sql_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_expired_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_extended_errcode_fnptr_t)(sqlite3*);
typedef int (*sqlite3_extended_result_codes_fnptr_t)(sqlite3*, int);
typedef int (*sqlite3_file_control_fnptr_t)(sqlite3*, const char*, int, void*);
typedef const char* (*sqlite3_filename_database_fnptr_t)(const char*);
typedef const char* (*sqlite3_filename_journal_fnptr_t)(const char*);
typedef const char* (*sqlite3_filename_wal_fnptr_t)(const char*);
typedef int (*sqlite3_finalize_fnptr_t)(sqlite3_stmt*);
typedef void (*sqlite3_free_fnptr_t)(void*);
typedef void (*sqlite3_free_filename_fnptr_t)(const char*);
typedef void (*sqlite3_free_table_fnptr_t)(char**);
typedef int (*sqlite3_get_autocommit_fnptr_t)(sqlite3*);
typedef void* (*sqlite3_get_auxdata_fnptr_t)(sqlite3_context*, int);
typedef int (*sqlite3_get_table_fnptr_t)(sqlite3*, const char*, char***, int*, int*, char**);
typedef int (*sqlite3_global_recover_fnptr_t)(void);
typedef sqlite3_int64 (*sqlite3_hard_heap_limit64_fnptr_t)(sqlite3_int64);
typedef int (*sqlite3_initialize_fnptr_t)(void);
typedef void (*sqlite3_interrupt_fnptr_t)(sqlite3*);
typedef int (*sqlite3_key_fnptr_t)(sqlite3*, const void*, int);
typedef int (*sqlite3_key_v2_fnptr_t)(sqlite3*, const char*, const void*, int);
typedef int (*sqlite3_keyword_check_fnptr_t)(const char*, int);
typedef int (*sqlite3_keyword_count_fnptr_t)(void);
typedef int (*sqlite3_keyword_name_fnptr_t)(int, const char**, int*);
typedef sqlite_int64 (*sqlite3_last_insert_rowid_fnptr_t)(sqlite3*);
typedef const char* (*sqlite3_libversion_fnptr_t)(void);
typedef int (*sqlite3_libversion_number_fnptr_t)(void);
typedef int (*sqlite3_limit_fnptr_t)(sqlite3*, int, int);
typedef int (*sqlite3_load_extension_fnptr_t)(sqlite3*, const char*, const char*, char**);
typedef void (*sqlite3_log_fnptr_t)(int, const char*, ...);
typedef void* (*sqlite3_malloc_fnptr_t)(int);
typedef void* (*sqlite3_malloc64_fnptr_t)(sqlite3_uint64);
typedef int (*sqlite3_memory_alarm_fnptr_t)(void (*)(void*, sqlite3_int64, int), void*, sqlite3_int64);
typedef sqlite3_int64 (*sqlite3_memory_highwater_fnptr_t)(int);
typedef sqlite3_int64 (*sqlite3_memory_used_fnptr_t)(void);
typedef char* (*sqlite3_mprintf_fnptr_t)(const char*, ...);
typedef sqlite3_uint64 (*sqlite3_msize_fnptr_t)(void*);
typedef sqlite3_mutex* (*sqlite3_mutex_alloc_fnptr_t)(int);
typedef void (*sqlite3_mutex_enter_fnptr_t)(sqlite3_mutex*);
typedef void (*sqlite3_mutex_free_fnptr_t)(sqlite3_mutex*);
typedef void (*sqlite3_mutex_leave_fnptr_t)(sqlite3_mutex*);
typedef int (*sqlite3_mutex_try_fnptr_t)(sqlite3_mutex*);
typedef sqlite3_stmt* (*sqlite3_next_stmt_fnptr_t)(sqlite3*, sqlite3_stmt*);
typedef int (*sqlite3_open_fnptr_t)(const char*, sqlite3**);
typedef int (*sqlite3_open_v2_fnptr_t)(const char*, sqlite3**, int, const char*);
typedef int (*sqlite3_open16_fnptr_t)(const void*, sqlite3**);
typedef int (*sqlite3_os_end_fnptr_t)(void);
typedef int (*sqlite3_os_init_fnptr_t)(void);
typedef int (*sqlite3_overload_function_fnptr_t)(sqlite3*, const char*, int);
typedef int (*sqlite3_prepare_fnptr_t)(sqlite3*, const char*, int, sqlite3_stmt**, const char**);
typedef int (*sqlite3_prepare_v2_fnptr_t)(sqlite3*, const char*, int, sqlite3_stmt**, const char**);
typedef int (*sqlite3_prepare_v3_fnptr_t)(sqlite3*, const char*, int, unsigned, sqlite3_stmt**, const char**);
typedef int (*sqlite3_prepare16_fnptr_t)(sqlite3*, const void*, int, sqlite3_stmt**, const void**);
typedef int (*sqlite3_prepare16_v2_fnptr_t)(sqlite3*, const void*, int, sqlite3_stmt**, const void**);
typedef int (*sqlite3_prepare16_v3_fnptr_t)(sqlite3*, const void*, int, unsigned, sqlite3_stmt**, const void**);
typedef void* (*sqlite3_profile_fnptr_t)(sqlite3*, void (*)(void*, const char*, sqlite_uint64), void*);
typedef void (*sqlite3_progress_handler_fnptr_t)(sqlite3*, int, int (*)(void*), void*);
typedef void (*sqlite3_randomness_fnptr_t)(int, void*);
typedef void* (*sqlite3_realloc_fnptr_t)(void*, int);
typedef void* (*sqlite3_realloc64_fnptr_t)(void*, sqlite3_uint64);
typedef int (*sqlite3_rekey_fnptr_t)(sqlite3*, const void*, int);
typedef int (*sqlite3_rekey_v2_fnptr_t)(sqlite3*, const char*, const void*, int);
typedef int (*sqlite3_release_memory_fnptr_t)(int);
typedef int (*sqlite3_reset_fnptr_t)(sqlite3_stmt*);
typedef void (*sqlite3_reset_auto_extension_fnptr_t)(void);
typedef void (*sqlite3_result_blob_fnptr_t)(sqlite3_context*, const void*, int, void (*)(void*));
typedef void (*sqlite3_result_blob64_fnptr_t)(sqlite3_context*, const void*, sqlite3_uint64, void (*)(void*));
typedef void (*sqlite3_result_double_fnptr_t)(sqlite3_context*, double);
typedef void (*sqlite3_result_error_fnptr_t)(sqlite3_context*, const char*, int);
typedef void (*sqlite3_result_error_code_fnptr_t)(sqlite3_context*, int);
typedef void (*sqlite3_result_error_nomem_fnptr_t)(sqlite3_context*);
typedef void (*sqlite3_result_error_toobig_fnptr_t)(sqlite3_context*);
typedef void (*sqlite3_result_error16_fnptr_t)(sqlite3_context*, const void*, int);
typedef void (*sqlite3_result_int_fnptr_t)(sqlite3_context*, int);
typedef void (*sqlite3_result_int64_fnptr_t)(sqlite3_context*, sqlite_int64);
typedef void (*sqlite3_result_null_fnptr_t)(sqlite3_context*);
typedef void (*sqlite3_result_pointer_fnptr_t)(sqlite3_context*, void*, const char*, void (*)(void*));
typedef void (*sqlite3_result_subtype_fnptr_t)(sqlite3_context*, unsigned);
typedef void (*sqlite3_result_text_fnptr_t)(sqlite3_context*, const char*, int, void (*)(void*));
typedef void (*sqlite3_result_text16_fnptr_t)(sqlite3_context*, const void*, int, void (*)(void*));
typedef void (*sqlite3_result_text16be_fnptr_t)(sqlite3_context*, const void*, int, void (*)(void*));
typedef void (*sqlite3_result_text16le_fnptr_t)(sqlite3_context*, const void*, int, void (*)(void*));
typedef void (*sqlite3_result_text64_fnptr_t)(sqlite3_context*, const char*, sqlite3_uint64, void (*)(void*), unsigned);
typedef void (*sqlite3_result_value_fnptr_t)(sqlite3_context*, sqlite3_value*);
typedef void (*sqlite3_result_zeroblob_fnptr_t)(sqlite3_context*, int);
typedef int (*sqlite3_result_zeroblob64_fnptr_t)(sqlite3_context*, sqlite3_uint64);
typedef void* (*sqlite3_rollback_hook_fnptr_t)(sqlite3*, void (*)(void*), void*);
typedef int (*sqlite3_rtree_geometry_callback_fnptr_t)(sqlite3*, const char*, int (*)(sqlite3_rtree_geometry*, int, sqlite3_rtree_dbl*, int*), void*);
typedef int (*sqlite3_rtree_query_callback_fnptr_t)(sqlite3*, const char*, int (*)(sqlite3_rtree_query_info*), void*, void (*)(void*));
typedef unsigned char* (*sqlite3_serialize_fnptr_t)(sqlite3*, const char*, sqlite3_int64*, unsigned);
typedef int (*sqlite3_set_authorizer_fnptr_t)(sqlite3*, int (*)(void*, int, const char*, const char*, const char*, const char*), void*);
typedef void (*sqlite3_set_auxdata_fnptr_t)(sqlite3_context*, int, void*, void (*)(void*));
typedef void (*sqlite3_set_last_insert_rowid_fnptr_t)(sqlite3*, sqlite3_int64);
typedef int (*sqlite3_shutdown_fnptr_t)(void);
typedef int (*sqlite3_sleep_fnptr_t)(int);
typedef int (*sqlite3_snapshot_cmp_fnptr_t)(sqlite3_snapshot*, sqlite3_snapshot*);
typedef void (*sqlite3_snapshot_free_fnptr_t)(sqlite3_snapshot*);
typedef int (*sqlite3_snapshot_get_fnptr_t)(sqlite3*, const char*, sqlite3_snapshot**);
typedef int (*sqlite3_snapshot_open_fnptr_t)(sqlite3*, const char*, sqlite3_snapshot*);
typedef int (*sqlite3_snapshot_recover_fnptr_t)(sqlite3*, const char*);
typedef char* (*sqlite3_snprintf_fnptr_t)(int, char*, const char*, ...);
typedef void (*sqlite3_soft_heap_limit_fnptr_t)(int);
typedef sqlite3_int64 (*sqlite3_soft_heap_limit64_fnptr_t)(sqlite3_int64);
typedef const char* (*sqlite3_sourceid_fnptr_t)(void);
typedef const char* (*sqlite3_sql_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_status_fnptr_t)(int, int*, int*, int);
typedef int (*sqlite3_status64_fnptr_t)(int, sqlite3_int64*, sqlite3_int64*, int);
typedef int (*sqlite3_step_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_stmt_busy_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_stmt_isexplain_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_stmt_readonly_fnptr_t)(sqlite3_stmt*);
typedef int (*sqlite3_stmt_status_fnptr_t)(sqlite3_stmt*, int, int);
typedef void (*sqlite3_str_append_fnptr_t)(sqlite3_str*, const char*, int);
typedef void (*sqlite3_str_appendall_fnptr_t)(sqlite3_str*, const char*);
typedef void (*sqlite3_str_appendchar_fnptr_t)(sqlite3_str*, int, char);
typedef void (*sqlite3_str_appendf_fnptr_t)(sqlite3_str*, const char*, ...);
typedef int (*sqlite3_str_errcode_fnptr_t)(sqlite3_str*);
typedef char* (*sqlite3_str_finish_fnptr_t)(sqlite3_str*);
typedef int (*sqlite3_str_length_fnptr_t)(sqlite3_str*);
typedef sqlite3_str* (*sqlite3_str_new_fnptr_t)(sqlite3*);
typedef void (*sqlite3_str_reset_fnptr_t)(sqlite3_str*);
typedef char* (*sqlite3_str_value_fnptr_t)(sqlite3_str*);
typedef void (*sqlite3_str_vappendf_fnptr_t)(sqlite3_str*, const char*, va_list);
typedef int (*sqlite3_strglob_fnptr_t)(const char*, const char*);
typedef int (*sqlite3_stricmp_fnptr_t)(const char*, const char*);
typedef int (*sqlite3_strlike_fnptr_t)(const char*, const char*, unsigned);
typedef int (*sqlite3_strnicmp_fnptr_t)(const char*, const char*, int);
typedef int (*sqlite3_system_errno_fnptr_t)(sqlite3*);
typedef int (*sqlite3_table_column_metadata_fnptr_t)(sqlite3*, const char*, const char*, const char*, char const**, char const**, int*, int*, int*);
typedef int (*sqlite3_test_control_fnptr_t)(int, ...);
typedef void (*sqlite3_thread_cleanup_fnptr_t)(void);
typedef int (*sqlite3_threadsafe_fnptr_t)(void);
typedef int (*sqlite3_total_changes_fnptr_t)(sqlite3*);
typedef sqlite3_int64 (*sqlite3_total_changes64_fnptr_t)(sqlite3*);
typedef void* (*sqlite3_trace_fnptr_t)(sqlite3*, void (*)(void*, const char*), void*);
typedef int (*sqlite3_trace_v2_fnptr_t)(sqlite3*, unsigned, int (*)(unsigned, void*, void*, void*), void*);
typedef int (*sqlite3_transfer_bindings_fnptr_t)(sqlite3_stmt*, sqlite3_stmt*);
typedef int (*sqlite3_txn_state_fnptr_t)(sqlite3*, const char*);
typedef void* (*sqlite3_update_hook_fnptr_t)(sqlite3*, void (*)(void*, int, char const*, char const*, sqlite_int64), void*);
typedef int (*sqlite3_uri_boolean_fnptr_t)(const char*, const char*, int);
typedef sqlite3_int64 (*sqlite3_uri_int64_fnptr_t)(const char*, const char*, sqlite3_int64);
typedef const char* (*sqlite3_uri_key_fnptr_t)(const char*, int);
typedef const char* (*sqlite3_uri_parameter_fnptr_t)(const char*, const char*);
typedef void* (*sqlite3_user_data_fnptr_t)(sqlite3_context*);
typedef const void* (*sqlite3_value_blob_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_bytes_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_bytes16_fnptr_t)(sqlite3_value*);
typedef double (*sqlite3_value_double_fnptr_t)(sqlite3_value*);
typedef sqlite3_value* (*sqlite3_value_dup_fnptr_t)(const sqlite3_value*);
typedef void (*sqlite3_value_free_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_frombind_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_int_fnptr_t)(sqlite3_value*);
typedef sqlite_int64 (*sqlite3_value_int64_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_nochange_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_numeric_type_fnptr_t)(sqlite3_value*);
typedef void* (*sqlite3_value_pointer_fnptr_t)(sqlite3_value*, const char*);
typedef unsigned int (*sqlite3_value_subtype_fnptr_t)(sqlite3_value*);
typedef const unsigned char* (*sqlite3_value_text_fnptr_t)(sqlite3_value*);
typedef const void* (*sqlite3_value_text16_fnptr_t)(sqlite3_value*);
typedef const void* (*sqlite3_value_text16be_fnptr_t)(sqlite3_value*);
typedef const void* (*sqlite3_value_text16le_fnptr_t)(sqlite3_value*);
typedef int (*sqlite3_value_type_fnptr_t)(sqlite3_value*);
typedef sqlite3_vfs* (*sqlite3_vfs_find_fnptr_t)(const char*);
typedef int (*sqlite3_vfs_register_fnptr_t)(sqlite3_vfs*, int);
typedef int (*sqlite3_vfs_unregister_fnptr_t)(sqlite3_vfs*);
typedef char* (*sqlite3_vmprintf_fnptr_t)(const char*, va_list);
typedef char* (*sqlite3_vsnprintf_fnptr_t)(int, char*, const char*, va_list);
typedef const char* (*sqlite3_vtab_collation_fnptr_t)(sqlite3_index_info*, int);
typedef int (*sqlite3_vtab_config_fnptr_t)(sqlite3*, int, ...);
typedef int (*sqlite3_vtab_distinct_fnptr_t)(sqlite3_index_info*);
typedef int (*sqlite3_vtab_in_fnptr_t)(sqlite3_index_info*, int, int);
typedef int (*sqlite3_vtab_in_first_fnptr_t)(sqlite3_value*, sqlite3_value**);
typedef int (*sqlite3_vtab_in_next_fnptr_t)(sqlite3_value*, sqlite3_value**);
typedef int (*sqlite3_vtab_nochange_fnptr_t)(sqlite3_context*);
typedef int (*sqlite3_vtab_on_conflict_fnptr_t)(sqlite3*);
typedef int (*sqlite3_vtab_rhs_value_fnptr_t)(sqlite3_index_info*, int, sqlite3_value**);
typedef int (*sqlite3_wal_autocheckpoint_fnptr_t)(sqlite3*, int);
typedef int (*sqlite3_wal_checkpoint_fnptr_t)(sqlite3*, const char*);
typedef int (*sqlite3_wal_checkpoint_v2_fnptr_t)(sqlite3*, const char*, int, int*, int*);
typedef void* (*sqlite3_wal_hook_fnptr_t)(sqlite3*, int (*)(void*, sqlite3*, const char*, int), void*);
typedef int (*sqlite3_win32_is_nt_fnptr_t)(void);
typedef char* (*sqlite3_win32_mbcs_to_utf8_fnptr_t)(const char*);
typedef char* (*sqlite3_win32_mbcs_to_utf8_v2_fnptr_t)(const char*, int);
typedef int (*sqlite3_win32_set_directory_fnptr_t)(unsigned long, void*);
typedef int (*sqlite3_win32_set_directory16_fnptr_t)(unsigned long, const void*);
typedef int (*sqlite3_win32_set_directory8_fnptr_t)(unsigned long, const char*);
typedef void (*sqlite3_win32_sleep_fnptr_t)(DWORD);
typedef char* (*sqlite3_win32_unicode_to_utf8_fnptr_t)(LPCWSTR);
typedef char* (*sqlite3_win32_utf8_to_mbcs_fnptr_t)(const char*);
typedef char* (*sqlite3_win32_utf8_to_mbcs_v2_fnptr_t)(const char*, int);
typedef LPWSTR (*sqlite3_win32_utf8_to_unicode_fnptr_t)(const char*);
typedef void (*sqlite3_win32_write_debug_fnptr_t)(const char*, int);
